global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web_app'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'postgres_db'
    static_configs:
      - targets: ['db:5432']
